#
# Copyright (c) 2013-2016, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

classes:
  org:
    seedstack:
      business:
        repositories:
          fixtures:
            defaultRepository: DefaultRepo
            TestAggregate2:
              defaultRepository: org.seedstack.business.repositories.fixtures.MyQualifier
        identity:
          fixtures:
            identityHandler: simpleUUID
        internal:
          assembler:
            dsl:
              fixture:
                identityHandler: simpleUUID

org:
  seedstack:
    toto: toto
transaction:
    defaultHandler: org.seedstack.seed.persistence.inmemory.internal.InMemoryTransactionHandler
business:
  events:
    publishRepositoryEvents: true
security:
  users:
    Anakin: imsodark
